language: node_js
node_js:
  - stable

addons:
  chrome:
    - stable

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn test -- --single-run

after_script:
  - ./cc-test-reporter after-build -t lcov -p $TRAVIS_HOME/coverage/lcov.info --exit-code $TRAVIS_TEST_RESULT
